services:
  # ---------------------------------------------------------------------------
  # 1. Prefect Server (API + UI)
  # ---------------------------------------------------------------------------
  prefect:
    image: prefecthq/prefect:3.4.8-python3.12-conda
    command: ["prefect", "server", "start", "--host", "0.0.0.0"]
    restart: unless-stopped
    ports:
      - "4200"
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@db:5432/prefect
      - PREFECT_UI_API_URL=${ENDPOINT}/api
    depends_on:
        db:
          condition: service_healthy
    healthcheck:
      test:
        - "CMD-SHELL"
        - >-
          python -c "import urllib.request, sys; sys.exit(0 if urllib.request.urlopen('http://localhost:4200/api/health', timeout=5).read().strip()==b'true' else 1)"
      interval: 15s
      timeout: 5s
    networks: [prefect-net]


  # ---------------------------------------------------------------------------
  # 2. Prefect Worker (process type)
  #    Listens to the *local-process* Work Pool created automatically on first run
  # ---------------------------------------------------------------------------
  prefect-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      prefect:
        condition: service_healthy
    environment:
      - PREFECT_API_URL=http://prefect:4200/api
      - PREFECT_LOGGING_LEVEL=INFO
      - WORKER_POOL_NAME=local-process
    # restart: unless-stopped
    networks: [prefect-net]

  # ---------------------------------------------------------------------------
  # 3. PostgreSQL Database
  # ---------------------------------------------------------------------------
  db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks: [prefect-net]

volumes:
  pgdata:

networks:
  prefect-net: